<?php
require 'vendor/autoload.php';

error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

use TCPDF;
class CustomPDF extends TCPDF {
    public function Header() {
        // Do nothing — this removes the black header line
    }
    public function Footer() {
        // Optional: remove footer too
    }
}
// Create new PDF
$pdf = new CustomPDF();

$pdf->AddPage();
// Disable header and footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
// Set font (use the name generated by tcpdf_addfont.php)
$pdf->SetFont('notoserifdevanagari', '', 14);

// Write mixed-language text
$txt = "Hello English text. नमस्ते, यह हिंदी में लिखा गया है।";

$pdf->Write(0, $txt);
$pdf->Output();
